dist: xenial
lang: c
script:
  - bash -x ./.travis.sh
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libsodium-dev
            - pkg-config
            - autoconf-archive
      env:
        - MATRIX_EVAL="export CC=gcc-5 && export CXX=g++-5"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - libsodium-dev
            - pkg-config
            - autoconf-archive
      env:
        - MATRIX_EVAL="export CC=gcc-6 && export CXX=g++-6"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libsodium-dev
            - pkg-config
            - autoconf-archive
      env:
        - MATRIX_EVAL="export CC=gcc-7 && export CXX=g++-7"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - libsodium-dev
            - pkg-config
            - autoconf-archive
      env:
        - MATRIX_EVAL="export CC=gcc-8 && export CXX=g++-8"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-6.0
          packages:
            - clang-6.0
            - libsodium-dev
            - pkg-config
            - autoconf-archive
      env:
        - MATRIX_EVAL="export CC=clang-6.0 && export CXX=clang++-6.0"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-7
          packages:
            - clang-7
            - libsodium-dev
            - pkg-config
            - autoconf-archive
      env:
        - MATRIX_EVAL="export CC=clang-7 && export CXX=clang++-7"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-8
          packages:
            - clang-8
            - libsodium-dev
            - pkg-config
            - autoconf-archive
      env:
        - MATRIX_EVAL="export CC=clang-8 && export CXX=clang++-8"
    - os: linux
      addons:
        apt:
          packages:
            - nodejs
      env:
        - MATRIX_EVAL="export LINT=1"
# Homebrew on travis-ci's OSX has been broken for a while
# e.g. https://travis-ci.org/cjdelisle/PacketCrypt/jobs/605520153
#    - os: osx
#      env:
#        - MATRIX_EVAL="export CC=clang && export CXX=clang++"
